# MERCENARY NAMES
merc_names = [
    "guts",
    "raphael",
    "eliza",
    "vasquez",
    "seraph",
    "emilia",
    "roberto",
    "william",
    "beckett",
    "freya",
    "astra",
    "raleigh",
    "thomas",
    "caleb",
    "frederick",
    "tybalt",
    "titus",
    "alexei",
    "marie",
    "harley",
    "michael",
    "sebastien",
    "sergei",
    "cassandra",
    "franz",
    "calvin",
    "helen",
    "sarai",
    "isolde",
    "othello",
    "laertes",
    "stanley",
    "alexander",
    "isobel",
    "madeleine",
]

# GUILD NAMES
guild_names = [
    "Band of the Hawk",
    "Order of the Hound",
    "House of the Bear",
]

# TEAM NAMES
# Team names are thematically associated to a guild name.
# If adding a new guild name above, add a new set of team names here also.
team_names = {
    "Band of the Hawk": [
        "Sparrows",
        "Kestrels",
        "Red Tails",
        "Ospreys",
        "Shikras",
        "Falcons",
    ],
    "Order of the Hound": [
        "Akitas",
        "Shepherds",
        "Shibas",
        "Wolves",
        "Jackals",
        "Diamond Dogs",
    ],
    "House of the Bear": [
        "Steel Claws",
        "Iron Furs",
        "Bloody Jaws",
    ],
}

# BOSS NAMES & TITLES
boss_names = [
    "griffith",
    "grux",
    "kerax",
    "vestral",
    "xevrain",
    "selin",
    "kefka",
    "tristan",
    "erlich",
    "eldreth",
    "revaz",
    "xavier",
    "bertrand",
    "terok",
    "malin",
    "zelk",
    "ereval",
    "relka",
    "orieth",
    "salazar",
    "kulth",
    "raleth",
    "loketh",
    "calstro",
    "zorieth",
]

boss_titles = [
    "the Terrible",
    "the Wicked",
    "the Dark Knight",
    "the Cleansing Flame",
    "the Crimson Promise",
    "the Broken Dreamer",
    "the Shattered Echo",
    "the Undying",
    "the Ghastly",
    "the Eternal",
    "the Unholy",
    "the Cursed",
    "The Ruinous Flame",
    "the Wretched",
    "the Corrupted",
    "the Bloody",
    "the Plagueridden",
    "the Oppressor",
    "the Blighted",
    "the Mad",
    "the Unhinged",
    "the Insane",
    "the Tortured",
    "the Awakened",
    "The Unspeakable",
]

# DUNGEON DESCRIPTION PIECES
dungeon_descriptors = {
    "a": [
        "Forgotten",
        "Haunted",
        "Forlorn",
        "Desolate",
        "Scourged",
        "Cursed",
        "Wailing",
        "Forsaken",
        "Scorched",
        "Frozen",
        "Corrupted",
        "Flooded",
        "Crumbling",
        "Tainted",
        "Hidden",
        "Lost",
        "Ruined",
        "Shattered",
        "Weeping",
        "Unclean",
        "Endless",
        "Scourged",
        "Bleeding",
        "Tortured",
        "Infernal",
    ],
    "b": [
        "Crypt",
        "Church",
        "Cathedral",
        "Sepulcher",
        "Warcamp",
        "Cave",
        "Tunnels",
        "Mausoleum",
        "Mine",
        "Forest",
        "Lair",
        "Tower",
        "Keep",
        "Ruins",
        "Oubliette",
        "Den",
        "Sanctum",
        "Hall",
        "Prison",
        "Plains",
        "Chambers",
        "Dungeon",
        "Fields",
        "Cavern",
        "Chasm",
    ],
}

enemy_types = [
    "Slime",
    "Goblin",
]

boss_types = [
    "Imp",
    "Lich",
    "Shadow",
]
